machine:
  pre:
    - git clone https://github.com/fabiolrodriguez/testops
test:
  override:
    - echo "I'm not testing anything here. Don't try this at home, Kids!"
build:
  prod:
    branch: master
    commands:
      - git push heroku master
