version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.1
    steps:
      - checkout
      - run: echo "A first hello"  
      - deploy:
          staging:
            branch: master
            heroku:
              appname: testeops
            command: 'git commit heroku master'
