version: 2
jobs:
  build:
    docker:
      - image: php:7.2.1
    steps:
      - checkout
	  

      - run:
	  name: Get sources
          command: git clone https://github.com/fabiolrodriguez/testops
	  
      - run:
          name: Run unit tests
          command: echo "testa aqui"

      - run:
          name: Setup Heroku
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      - run:
          name: Deploy to Heroku
          command: |
            git push heroku master
